INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (1, 'Mecânico', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (2, 'Eletricista', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (3, 'Encanador', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (4, 'Pedreiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (5, 'Pintor', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (6, 'Diarista', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (7, 'Eleticista de Automóvel', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (8, 'Personal Trainer', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (9, 'Porteiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (10, 'Jardineiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (11, 'Segurança', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (12, 'Cuidador de Pets', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (13, 'Professor Particular', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (14, 'Vidraceiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (15, 'Carroceiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (16, 'Lanterneiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (17, 'Piscineiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (18, 'Marceneiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (19, 'Serralheiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (20, 'Carpinteiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (21, 'Azulejista', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (22, 'Gesseiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (23, 'Montador de móveis', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (24, 'Calheiro', 99.99);
INSERT INTO TB_SERVICO(id_servico, nome_servico, preco) VALUES (25, 'Soldador', 99.99);